# Generated by Django 5.2 on 2025-04-21 04:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Habit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('health', 'Здоровье'), ('productivity', 'Продуктивность'), ('learning', 'Обучение'), ('relationships', 'Отношения'), ('finance', 'Финансы')], max_length=20)),
                ('description', models.TextField(blank=True)),
                ('days_goal', models.PositiveIntegerField(default=30)),
                ('color_class', models.CharField(choices=[('bg-red-100 text-red-800', 'Красный'), ('bg-blue-100 text-blue-800', 'Синий'), ('bg-green-100 text-green-800', 'Зеленый'), ('bg-yellow-100 text-yellow-800', 'Желтый'), ('bg-purple-100 text-purple-800', 'Фиолетовый'), ('bg-pink-100 text-pink-800', 'Розовый')], default='bg-gray-100 text-gray-800', max_length=50)),
                ('reminder', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='HabitSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.IntegerField(choices=[(0, 'Воскресенье'), (1, 'Понедельник'), (2, 'Вторник'), (3, 'Среда'), (4, 'Четверг'), (5, 'Пятница'), (6, 'Суббота')])),
                ('habit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedule', to='habits.habit')),
            ],
            options={
                'unique_together': {('habit', 'day_of_week')},
            },
        ),
    ]
