# Generated by Django 5.2 on 2025-05-19 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='moodentry',
            name='is_favorite',
            field=models.BooleanField(default=False, verbose_name='Избранное'),
        ),
    ]
