# Generated by Django 5.2 on 2025-04-21 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='moodentry',
            options={'ordering': ['-date'], 'verbose_name_plural': 'Mood Entries'},
        ),
        migrations.AddField(
            model_name='moodentry',
            name='last_edited',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
