# Generated by Django 5.2 on 2025-05-11 12:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0002_alter_habitschedule_day_of_week'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='habitcompletion',
            constraint=models.CheckConstraint(condition=models.Q(('date__lte', datetime.date(2025, 5, 11))), name='date_cannot_be_in_future'),
        ),
    ]
