# Generated by Django 5.2 on 2025-05-19 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0002_moodentry_is_favorite'),
    ]

    operations = [
        migrations.AddField(
            model_name='moodentry',
            name='favorite_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='moodentry',
            name='is_favorite',
            field=models.BooleanField(default=False),
        ),
    ]
