# Generated by Django 5.2 on 2025-05-19 19:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0003_moodentry_favorite_date_alter_moodentry_is_favorite'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='moodentry',
            name='favorite_date',
        ),
    ]
