# Generated by Django 5.2 on 2025-05-05 05:52

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_options_alter_user_groups_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, default='images/default_avatar.png', null=True, upload_to=accounts.models.user_avatar_path, verbose_name='Аватар'),
        ),
    ]
