# Generated by Django 5.2 on 2025-05-05 09:58

from django.db import migrations


def add_registration_achievement(apps, schema_editor):
    User = apps.get_model('accounts', 'User')
    Achievement = apps.get_model('accounts', 'Achievement')

    for user in User.objects.all():
        if not Achievement.objects.filter(user=user, title='Первый шаг').exists():
            Achievement.objects.create(
                user=user,
                title='Первый шаг',
                description='Вы успешно зарегистрировались в системе!',
                icon='🎉',
                is_unlocked=True
            )


class Migration(migrations.Migration):
    dependencies = [
        # Укажите последнюю миграцию вашего приложения accounts
    ]

    operations = [
        migrations.RunPython(add_registration_achievement),
    ]